### ISSUE TITLE
Unable to set ports to none

### ISSUE THREAD

**Issue by Shnoulle** [univlorraine/limesurvey-cas#1]
If you have a cas without port (80 is default), setting to empty string replace it by 0. Setting to 80/443 can go to a broken link (unconnect redirect) (tested, but don't know cas configuration).

I think we must allow empty to port.

**Comment by goyome** [comment]
I agree with you. Empty port shouldn't break the plugin. But considering 80 to be the default port for CAS annoys me for security reason. I would prefer using the default installation port (8443) or the most commonly used one (443). I think I'm going to replace empty CAS port by 443.

About the second part of your message, Setting the port to 80 or 443 should work depending on your server configuration. To validate that your settings are the right ones, you can try to contact your CAS server in your browser using : 
_CAS_Server_:_CAS_portCAS_uri_/login

The CAS URI setting, if not empty, should start with a slash.

I'll wait for your feedback before updating the code

**Comment by Shnoulle** [comment]
I ask to the user test with 443 ... maybe we made an error this mornig on testing. But set '' to port seems to fix the issue too ;)

**Comment by Shnoulle** [comment]
Set to 443 fix it :)

PS: Thanks a lot, great plugin
