### ISSUE TITLE
session_write_close() sur CAS avec maj limesurvey 3.8.0

### ISSUE THREAD

**Issue by sabineCa** [univlorraine/limesurvey-cas#14]
Bonjour, 
lorsque je passe la maj LS vers la version 3.8.0 et que j'essaie de me connecter par la suite, j'obtiens une erreur php : session_write_close(): write failed: No space left on device (28) .
Dans la stacktrace, cela concerne le plugin AuthCAS. Est-ce que cela vous parle ? 

Merci 
Cordialement

**Comment by goyome** [comment]
Bonjour,

Je n'ai jamais rencontré l'erreur mais à première vue, on dirait qu'il ne parvient pas à écrire sa session.
Il faudrait commencer par vérifier, au niveau système, que la partition n'est pas pleine et si elle ne l'est pas, vérifier le paramètrage php et les droits sur le dossier pour vous assurer qu'il est possible de créer des sessions à l'emplacement défini dans la configuration.

Bonne journée

**Comment by sabineCa** [comment]
Bonjour,
merci pour votre réponse, effectivement, le cache était plein. Je n'avais pas fait attention au vue des nombreuses maj que je suis en train de passer pour limesurvey mais après avoir fait un gros ménage, cela fonctionne à nouveau.
Merci pour votre aide et pour votre plugin qui nous est bien utile chez nous.

Cordialement
