### ISSUE TITLE
Filtre sur requête ldap

### ISSUE THREAD

**Issue by nicktruch** [univlorraine/limesurvey-cas#16]
Bonjour

Pensez-vous qu'il serait envisageable de créer un fork de votre plugin qui, sur la base de l'identifiant saisi dans le formulaire, fasse une requête ldap de façon à - par exemple - conditionner l'accès à limesurvey à l'appartenance à un groupe ou un profil donné ?

Nicolas

**Comment by goyome** [comment]
Bonjour,

Si vous souhaitez filtrer l'accès à la partie admin/création de questionnaires, cette fonctionnalité est déjà existante.
Pour cela, sélectionnez "User creation on the first connection", vous pourrez alors renseigner le champ "Optional extra LDAP filter to be ANDed to the basic (searchuserattribute=username) filter" avec le filtre ldap souhaité.

Si vous souhaitez utiliser la cassification pour authentifier les répondants à un questionnaire, je vous invite à regarder les pistes évoquées dans l'issue ci-dessous :
https://github.com/univlorraine/limesurvey-cas/issues/5

Bonne journée

**Comment by nicktruch** [comment]
Re
J'essaye depuis votre dernier message de paramétrer le plugin comme indiqué mais je bloque sur une erreur 500 : "CDbCommand n'a pas pu exécuter la commande SQL: SQLSTATE[HY000]: General error: 1364 Field 'full_name' doesn't have a default value".
J'ai essayé en ne précisant aucun filtre LDAP : sans succès.
J'ai aussi essayé tous les paramétrages concernant la version de ldap, l'option referals ainsi que le Start-TLS, sans plus de succès.
Lorsque je choisis "No, don't create user automaticaly" tout fonctionne.
Dans quel sens me conseilleriez-vous de creuser ?
Bien à vous,
Nicolas

**Comment by goyome** [comment]
Je pense qu'il s'agit d'une erreur liée au non paramétrage du champ "Attribute to display the user fullname".
Chez nous,  à titre d'exemple, on utilise la valeur "displayName".

N'oubliez pas de paramétrer le fichier config.php avec les valeurs ci-dessous pour définir les droits par défaut des comptes créés :
'auth_cas_autocreate_permissions' => array(
          'surveys' => array('create'=>true)
  ),
  'auth_cas_template_list' => array(
          'default',
          'limespired'
  ),

Bonne journée

**Comment by nicktruch** [comment]
Idem chez nous à Lyon2 (sommes sur Supann comme vous je pense).
Le displayName ne passant pas, je l'ai remplacé par mail puis par cn et c'est passé... étrange : cela signifie un problème spécifiquement lié à l'attribut "displayName"...
Merci pour vos retours et bonne journée
