### ISSUE TITLE
Valeurs de configuration par défaut dans config.php

### ISSUE THREAD

**Issue by nicktruch** [univlorraine/limesurvey-cas#17]
Dans le fichier config.php on définit les droits par défaut des comptes créés :
```
'auth_cas_autocreate_permissions' => array(
'surveys' => array('create'=>true)
),
```
A-t-on la possibilité d'ajouter d'autres droits par défaut comme par exemple le droit de créer des utilisateurs ou d'en supprimer ?

Nicolas
Ps. votre plugin est une pure merveille, surtout depuis que j'arrive à la faire marcher ;-)

**Comment by goyome** [comment]
Il est possible de donner les mêmes droits qu'à la définition des droits dans l'interface graphique.
Il vous suffit de regarder les "id" des cases à cocher.
Par exemple, l'identifiant pour donner les droits  de création d'un questionnaire est perm_surveys_create, ce qui a donné le droit que nous utilisons et que j'ai mis en exemple.

Dans votre cas, les identifiants sont perm_users_create et perm_users_delete, ce qui donnerait une configuration du type :

```
'auth_cas_autocreate_permissions' => array(
'surveys' => array('create'=>true),
'users' => array('create'=>true, 'delete'=>true)
),
```

Il suffit d'ajouter les entrées voulues au tableau.

**Comment by nicktruch** [comment]
Merci, c'est juste fabuleux.

**Comment by nicktruch** [comment]
Juste un petit mémo pour signaler que pour donner les droits de création/édition/suppression de users, le paramétrage à utiliser est :
`'users' => array('create'=>true, 'read'=>true, 'delete'=>true, 'update'=>true),`

Pour les autres droits, les commandes a maxima sont les suivantes, à vous de choisir le niveau de droits que vous voulez donner  :
```
'usergroups' => array('create'=>true, 'read'=>true, 'delete'=>true, 'update'=>true),
'templates' => array('create'=>true, 'read'=>true, 'delete'=>true, 'update'=>true, 'import'=>true, 'export'=>true),
'labelsets' => array('create'=>true, 'read'=>true, 'delete'=>true, 'update'=>true, 'import'=>true, 'export'=>true)
```
