### ISSUE TITLE
[feature][publication] Add plugin on LimeStore

### ISSUE THREAD

**Issue by Shnoulle** [univlorraine/limesurvey-cas#18]
Salut,

Votre plugin est dispo sur limesurvey.org, c'est cool (merci à vous) : https://www.limesurvey.org/fr/component/sobipro/85-authcas

Actuellement, l'équipe de LimeSurvey GMBH travail sur une autre façon de publier/télépcharger les plugin. Le [LimeStore](https://www.limesurvey.org/fr/limestore). 
Dans les futures versions : il sera possible de gérer les plugins un peu à la manière de wordpress ou spip ou … dans l'interface admin. Mais il est tout à fait possible d'envoyer le plugin pour les version 2 et 3 dès maintenant.

Sur le forum : [LimeStore purchase models](https://www.limesurvey.org/fr/forum/development/118840-limestore-purchase-models)  (la vente sera possible à terme, mais les plugin libre et gratuit sont appréciés aussi :)).

Je peux créer un pull request pour y ajouter le config.xml (avec compatibilité 2 et 3) qui vous permettra d'envoyer le zip si vous le souhaitez :). Ce sera avec un grand plaisir.

**Comment by Shnoulle** [comment]
config.xml in https://github.com/univlorraine/limesurvey-cas/pull/21

**Comment by goyome** [comment]
Bonjour,

Je viens de regarder comment ajouter l'extension au limestore mais dans la page de description, c'est toujours indiqué TODO dans la section "How do I become a third-party developer? " :P (https://manual.limesurvey.org/LimeStore_extension_development)

Je suppose que vous êtes déjà déclaré en tant que dév LS. Je vous invite, si vous le souhaitez, à déposer cette extension à votre nom. Ça me semble tout à fait cohérent puisque vous avez fait tout le travail de mise à jour.
Si ça ne vous intéresse pas, savez-vous qui je dois contacter pour demander une validation officielle et la possibilité de déposer l'extension ?

Merci d'avance

**Comment by Shnoulle** [comment]
Le store est fermé actuellement … je rouvrirais au moment voulu
