### ISSUE TITLE
[PHP version] Deprecated: __autoload() is deprecated, use spl_autoload_register()

### ISSUE THREAD

**Issue by Shnoulle** [univlorraine/limesurvey-cas#20]
When activate plugin, with PHP 7.4 and debug set : receive error
`( ! ) Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in /data/shnoulle/Développements/LimeSurvey external Plugins/limesurvey-cas/AuthCAS/third_party/CAS/source/CAS/Autoload.php on line 98`

Maybe time to update last php-CAS version ? 

https://github.com/apereo/phpCAS/releases/tag/1.4.0 maybe ?

**Comment by Shnoulle** [comment]
PS : i can do a real test only if i have a CAS server for testing purpose ;)

**Comment by goyome** [comment]
Hi,

Thanks for pointing that out. We're gonna make some test to upgrade phpCAS.
Sorry but we won't maintain an public instance of a CAS server for testing purpose :)

**Comment by Shnoulle** [comment]
> Sorry but we won't maintain an public instance of a CAS server for testing purpose :)

🤣 totally understand this !

Maybe i have a task for LimeSurvey 5.X compatibility upgrade of plugin.

**Comment by Shnoulle** [comment]
https://github.com/univlorraine/limesurvey-cas/pull/21

Maybe you can check if it work for you ?
I just make a micro update for auth_CAS not set mean : can log in.

**Comment by goyome** [comment]
Thanks for solving the problem yourself. I'm sorry for the lack of reaction :sweat_smile:

**Comment by Shnoulle** [comment]
> Thanks for solving the problem yourself. I'm sorry for the lack of reaction 😅

No problem ! Thanks for your good work.
