### ISSUE TITLE
Plug in compatibility with limesurvey 6.x

### ISSUE THREAD

**Issue by mhetru** [univlorraine/limesurvey-cas#23]
Hi, 
Have you planed to upgrade this plugin to the lastest version of limesurvey 6.x ?

Best regards.

**Comment by mhetru** [comment]
Hello,
i have just modified the file AuthCAS/config.xml with adding this line : 
`<version>6</version>`
and it works
my question : is it ok for you ?
you validate ?
Best regards,

**Comment by goyome** [comment]
Hi Mathieu,

We have been using it on a 6.3 limesurvey for several months now without any problem.
I'm going to do the update. 

Regards

**Comment by goyome** [comment]
Hi Mathieu,

I've added a commit to add the compatibility for version 6 but after verifying on our server, it's working without this modification to the config.xml.

Regards
