### ISSUE TITLE
Question about Using CAS Plugin for LimeSurvey Authentication in a Questionnaire

### ISSUE THREAD

**Issue by mbdeme** [univlorraine/limesurvey-cas#24]
Hi,

I am exploring the use of the CAS (Central Authentication Service) plugin for LimeSurvey and I have a specific scenario that I'm trying to address. I would like to implement CAS authentication, but only for certain questionnaires, not all of them.

Is it possible?

Thanks in advance

**Comment by mbdeme** [comment]
I forgot to add a clarification, I use version 5 of Limesurvey and I plan to update to version 6.
Thanks.

**Comment by goyome** [comment]
Hi,

This module provides backend authentication. 
The authentication is for survey creator. I'm not sure that it matches with your use case.
By the way, when activated, you can still use local authentication thanks to the page index.php/admin/authentication/sa/login?noAuthCAS=true

Hope this answer is clear enough.

**Comment by mbdeme** [comment]
Thank you for your reply;
By the way I think it's a little different from our use case.
I would like to enable or not CAS authentication depending on the questionnaire.

**Comment by goyome** [comment]
Well, I'm sorry but this plugin is not meant for that, only to identify user during admin access…

**Comment by mbdeme** [comment]
Ok I see in any case thank you for your availability
