### ISSUE TITLE
noAuthCAS=true ne fonctionne plus, impossible de m'authentifier avec un utilisateur "local"

### ISSUE THREAD

**Issue by Aurely9n** [univlorraine/limesurvey-cas#25]
Bonjour,

Je ne parviens plus à désengager l'authentification via CAS lorsque j'utilise l'URL "ls_url/index.php/admin/authentication/sa/login?noAuthCAS=true".
Lorsque j'essaie d'authentifier mon utilisateur qui possède un compte local par cette URL, je suis automatiquement redirigé vers l'authentification CAS. Pourtant cette URL fonctionnait avant.

C'est problématique car j'ai plusieurs utilisateur qui doivent utiliser cette URL noAuthCAS (car elles ne font pas partie de mon organisation). De plus, je ne peux plus utiliser l'API RemoteControl car mon utilisateur local API ne peux plus s'authentifier à LimeSurvey.

Cordialement,

**Comment by goyome** [comment]
Bonjour,

Quelle manipulation avez-vous faite qui a engendré le changement de comportement ?
Montée de version de LS, du plugin, … ?
Quelles sont les versions actuellement utilisées et celles utilisées avant ?

Cordialement

**Comment by Aurely9n** [comment]
J'ai la version 6.4.9+240226 de limesurvey et j'ai installé la branche mater de votre plugin "AuthCAS" (pour mettre à jour mon ancienne version).

Je clos Ce ticket.
L'erreur venait probablement du mdp de l'utilisateur qui n'avait pas été correctement initialisé.
Tout semble fonctionner correctement maintenant.
Merci pour votre attention et veuillez m'excuser pour le dérangement inutile.

Cordialement,

P.s: Pourriez-vous faire une release de la dernière version fonctionelle ? La dernière release n'est que pour la compatibilité limeSurvey v5.

**Comment by goyome** [comment]
Bonne idée. Je viens d'ajouter le tag v6.
