### ISSUE TITLE
Could not parse config.xml file

### ISSUE THREAD

**Issue by xezpeleta** [univlorraine/limesurvey-cas#26]
Hi!!

First of all, thanks for making this project available.

I'm trying to install this plugin on Limesurvey 6.6.7, and I get the following error:

```
The plugin could not be installed or updated: Could not parse config.xml file
```

I downloaded the latest code from the GitHub repository, and I generated a zip file following the 5.x plugin structure.

The zip file is uploaded and processed correctly:

![Screenshot 2024-10-29](https://github.com/user-attachments/assets/10875e17-f0df-4409-9e24-fff0e0771dad)

But the install button triggers an error:

![Screenshot 2024-10-29](https://github.com/user-attachments/assets/1e073f09-5e0f-4b6a-ad85-225dff8a1845)

Thank you!!!

**Comment by goyome** [comment]
Hi, 

We are using the 6.6.6+ version here. I hope this small difference doesn't cause the problem.

Maybe you made a mistake when filling the config.xml file before zipping the file and the format is not recognized correctly.

**Comment by xezpeleta** [comment]
You're right! Turns out I made a mistake when creating the zip file. I had it one level higher than needed. After moving everything one level deeper, it worked fine. Thanks for pointing that out!
