### ISSUE TITLE
Cas authentication for Forms

### ISSUE THREAD

**Issue by acidjames** [univlorraine/limesurvey-cas#5]
Hi guys,

This is a very nice initiative. I was wondering if you were working on a CAS authentication for the forms themselves (not the admin)? I guess you know what i mean :)

Cheers from UnivToulouse !
James

**Comment by goyome** [comment]
Hi,

We never try to add a CAS authentication to the forms so far. You could use mod_cas to add authentication to the whole limesurvey instance but I'm pretty sure that you want to be more specific...

Cheers

Guillaume

**Comment by acidjames** [comment]
For those who were wondering how to use limesurvey with CAS, i'm pretty sure it's possible using Remotecontrol2API : https://manual.limesurvey.org/RemoteControl_2_API

It needs some programming but should be quite easy, i'm probably going to test it this year.

Cheers,

**Comment by Shnoulle** [comment]
Think best is to use beforeRegisterEvent , but totally unrelated to AuthCAS ;)

**Comment by goyome** [comment]
Thanks Denis for your suggestion. 
I post here a link to an example of your plugin using beforeRegisterEvent and close this issue.

https://framagit.org/SondagePro-LimeSurvey-plugin/registerQuick

Cheers

**Comment by Shnoulle** [comment]
@goyome then, i think we can have (when someone have time or/and money)

1. CasLibraryHelper : just https://github.com/univlorraine/limesurvey-cas/tree/master/AuthCAS/third_party/CAS with a alias to get call easily
2. AuthCas : https://github.com/univlorraine/limesurvey-cas/blob/master/AuthCAS/AuthCAS.php using the library
3. registerCas : something with beforeRegisterEvent

Something related too about register : https://www.limesurvey.org/limestore?view=extensiondetails&id=42
