### ISSUE TITLE
Nginx : Problème avec le noAuthCAS

### ISSUE THREAD

**Issue by sparadrus** [univlorraine/limesurvey-cas#6]
Bonjour, félicitation pour ce merveilleux module que j'ai mis en prod depuis 1 an maintenant :+1:  

J'ai migrer sur Nginx 1.10, tout fonctionne à merveille sauf la réécriture d'url qu'il faut je creuse... 
Je ne sais pas si c'est lié mais je n'arrive pas à accéder à la connexion utilisateur interne de LimeSurvey via :

https://monsite/sondage/?r=admin/authentication/sa/login?noAuthCAS=true

On peut remarquer qu'à la place du /sondage/index.php/admin/ nous avons /sondage/?r=admin/
C'est que pour que LS fonctionne avec nginx, il faut changer certains paramètres dans /application/config/config.php :

`'urlManager' => array(
                        //'urlFormat' => 'path', // Pour Apache
                        'urlFormat' => 'get', // Pour nginx
                        'rules' => require('routes.php'),
                        //'showScriptName' => true, // Pour Apache
                        'showScriptName' => false, // Pour nginx
                ),`

Alors j'avoue ne pas avoir vérifier avant migration vers Apache... j’essaierai dès que je peut.

Mais est-ce qu'un fichier de log peut vous aider à m'aider :) ?
Ou le mode Développeur de FF afin de tracer les url...?

Votre aide me sera très précieuse, merci par avance.

**Comment by goyome** [comment]
Bonjour,

Je n'ai jamais utilisé nginx avec limesurvey et je n'ai jamais modifié les paramètres de génération d'url.
Je n'ai malheureusement pas non plus le temps de tester.

Toutefois à première vue, je dirais que l'url que vous utilisez est fausse. 
En effet, nginx vous oblige à travailler avec des paramètres get et le paramètre supplémentaire pour demander l'authentification interne en est aussi un. Il faudrait donc les séparer par &
Ce qui donnerait :

https://monsite/sondage/?r=admin/authentication/sa/login&noAuthCAS=true

J'espère que ça résoudra votre problème.

Bonne journée

**Comment by sparadrus** [comment]
Bonjour,
Effectivement problème résolu !
https://monsite/sondage/?r=admin/authentication/sa/login&noAuthCAS=true fonctionne :)
Merci pour votre réponse si rapide.

J'en profite :) J'ai un autre problème en ouvrant le menu Plugin CAS de LS il y a quelques semaines, j'ai voulu voir les paramètres par attributs CAS et j'ai perdu ma conf :/
Je réussi à être redirigé vers le cas et à me logguer, mais si l'utilisateur n'existe pas il ne le crée plus..
Voici mes paramètres (Je suis sous AD 2012 R2) : 

casAuthServer   "portailcas.monsite.fr"
casAuthPort     "443"
casAuthUri  "\/cas"
casVersion  "2.0"
autoCreate  "1"

casLoginAttr    null
casFullnameAttr     null
casMailAttr     null

server  "ldap:\/\/192.168.1.1"
ldapport    "389"
ldapversion     "2"
ldapoptreferrals    "0"
ldaptls     null
searchuserattribute     "sAMAccountName"
usersearchbase  "OU=MesUsers,DC=Net,DC=Loc"
extrauserfilter     ""
binddn  "DN=Bind,OU=MesUsers,DC=Net,DC=Loc"
bindpwd     "MonPwUserAd"
mailattribute   "mail"
fullnameattribute   "cn"

Merci encore

**Comment by goyome** [comment]
Désolé mais je n'ai pas compris le problème que vous avez rencontré avec les attributs CAS. 
Vous n'avez pas retrouvé vos paramètres initiaux en revenant à un paramètrage par création avec LDAP ? Ou ils ne sont plus pris en compte ?
Les paramètres que vous listez ici sont extraits de la base de données ? Il y a des attributs CAS et des attributs LDAP. Ils ne sont pas censés être utilisés simultanément.
Par ailleurs, avez-vous des erreurs au niveau des logs du serveur ou sur l'interface au moment où la création ne se produit pas ?

Quoiqu'il en soit, je clos cette demande car le problème n'est plus lié au titre initial. Merci de créer une nouvelle demande en complétant les informations.
