### ISSUE TITLE
Nginx : Problème création utilisateur au 1er login

### ISSUE THREAD

**Issue by sparadrus** [univlorraine/limesurvey-cas#7]
Bonsoir,

En faisant des tests il y a quelques semaines et en voulant expérimenter les attributs CAS de votre plugin, j'ai perdu ma conf :)

Après migration vers Nginx 1.10, j'ai tenter de les remettre.

Je n'arrive plus à créer des utilisateurs au 1er login.
Cela engendre des Too Many Redirects qui aboutissent à un blocage du à des logins successifs (entre 20 et 40 tentatives de logins lors d'un test unitaire)

**Voici mes logs du cas suite à une tentative :**

2016-05-25 22:44:16,335 INFO [org.jasig.cas.authentication.AuthenticationManager                                                                                                                                                             Impl] - <org.jasig.cas.adaptors.ldap.BindLdapAuthenticationHandler successfully                                                                                                                                                              authenticated [username: USER1]>
2016-05-25 22:44:16,335 INFO [org.jasig.cas.authentication.AuthenticationManager                                                                                                                                                             Impl] - <Resolved principal USER1>
2016-05-25 22:44:16,335 INFO [org.jasig.cas.authentication.AuthenticationManager                                                                                                                                                             Impl] - <org.jasig.cas.adaptors.ldap.BindLdapAuthenticationHandler@59382884 auth                                                                                                                                                             enticated USER1 with credential [username: USER1].>
#2016-05-25 22:44:16,336 INFO [com.github.inspektr.audit.support.Slf4jLoggingAudi                                                                                                                                                             tTrailManager] - <Audit trail record BEGIN

WHO: [username: USER1]
WHAT: supplied credentials: [username: USER1]
ACTION: AUTHENTICATION_SUCCESS
APPLICATION: CAS
WHEN: Wed May 25 22:44:16 CEST 2016
CLIENT IP ADDRESS: 127.0.0.1
# SERVER IP ADDRESS: 127.0.0.1

> # 2016-05-25 22:44:16,336 INFO [com.github.inspektr.audit.support.Slf4jLoggingAudi                                                                                                                                                             tTrailManager] - <Audit trail record BEGIN
> 
> WHO: [username: USER1]
> WHAT: TGT-533-zP16ZxyxMhKkiWXcWXncKUpjmYN0jEeemD3At1fop3FKtMtMjH-cas01.example.o                                                                                                                                                             rg
> ACTION: TICKET_GRANTING_TICKET_CREATED
> APPLICATION: CAS
> WHEN: Wed May 25 22:44:16 CEST 2016
> CLIENT IP ADDRESS: 127.0.0.1
> # SERVER IP ADDRESS: 127.0.0.1
> 
> 2016-05-25 22:44:16,336 INFO [org.jasig.cas.CentralAuthenticationServiceImpl] -                                                                                                                                                              <Granted service ticket [ST-899-POGa35IjUdSgyeJfyenQ-cas01.example.org] for serv                                                                                                                                                             ice [https://monsite.fr/sondage/?r=admin/authentication/sa/logi                                                                                                                                                             n] for user [USER1]>
> # 2016-05-25 22:44:16,336 INFO [com.github.inspektr.audit.support.Slf4jLoggingAudi                                                                                                                                                             tTrailManager] - <Audit trail record BEGIN
> 
> WHO: USER1
> WHAT: ST-899-POGa35IjUdSgyeJfyenQ-cas01.example.org for **https://monsite.fr/sondage/?r=admin/authentication/sa/login**
> ACTION: SERVICE_TICKET_CREATED
> APPLICATION: CAS
> WHEN: Wed May 25 22:44:16 CEST 2016
> CLIENT IP ADDRESS: 127.0.0.1
> # SERVER IP ADDRESS: 127.0.0.1
> # 2016-05-25 22:44:16,458 INFO [com.github.inspektr.audit.support.Slf4jLoggingAudi                                                                                                                                                             tTrailManager] - <Audit trail record BEGIN
> 
> WHO: audit:unknown
> WHAT: ST-899-POGa35IjUdSgyeJfyenQ-cas01.example.org
> ACTION: SERVICE_TICKET_VALIDATED
> APPLICATION: CAS
> WHEN: Wed May 25 22:44:16 CEST 2016
> CLIENT IP ADDRESS: 127.0.0.1
> # SERVER IP ADDRESS: 127.0.0.1

**Mes paramètres bdd pour votre plugin :** 

casAuthServer "portailcas.monsite.fr"
casAuthPort "443"
casAuthUri "\/cas"
casVersion "2.0"
autoCreate "1"

casLoginAttr null
casFullnameAttr null
casMailAttr null

server "ldap:\/\/192.168.1.1"
ldapport "389"
ldapversion "2"
ldapoptreferrals "0"
ldaptls null
searchuserattribute "sAMAccountName"
usersearchbase "OU=MesUsers,DC=Net,DC=Loc"
extrauserfilter ""
binddn "DN=Bind,OU=MesUsers,DC=Net,DC=Loc"
bindpwd "MonPwUserAd"
mailattribute "mail"
fullnameattribute "cn"

Suite à mon précedent post, je viens d'essayer d'enlever les attributs LDAP dans votre extension et ne laisser que le CAS. Même problème.

**Une partie de mon vhost nginx :**

```
    location / {
             try_files $uri $uri/ /index.php?q=$uri&$args;
    }
    location ~ \.php$ {
            include snippets/fastcgi-php.conf;

            fastcgi_pass unix:/run/php/php7.0-fpm.sock;
            fastcgi_param  SERVER_NAME      $host;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;

            fastcgi_cache nginxcache;
            fastcgi_cache_key $host$request_uri;
            fastcgi_cache_valid any 1h;
            fastcgi_cache_use_stale off;

           fastcgi_intercept_errors on;
    }
```

Et enfin le config.php adapté à Nginx

'urlManager' => array( 

//'urlFormat' => 'path', // Pour Apache 
'urlFormat' => 'get', // Pour nginx 

'rules' => require('routes.php'), 

//'showScriptName' => true, // Pour Apache 
'showScriptName' => false, // Pour nginx ),

Merci par avance pour votre aide
Cordialement

**Comment by goyome** [comment]
Bonjour,

Je n'ai jamais eu le temps de me pencher sur votre soucis. Désolé.
Étant donné la date, je clos l'issue.

Bonne journée
