### ISSUE TITLE
next update ?

### ISSUE THREAD

**Issue by sabineCa** [univlorraine/limesurvey-cas#9]
hello, 
i'm using the limesurvey application and i can't to update to the last version (3.0.1) of this application because of the version of your plugin.
An Employee told me this : " l'arborescence et les espaces de noms des plugins a été changé dans la V3, les plugins doivent donc être mis à jour par leur auteur avant de pouvoir fonctionner. "

do you make a compatible update soon ?
thank you and have a good day

**Comment by goyome** [comment]
We haven't planned to update for the moment but feel free to send a pull request if you make the update before us.
As soon as we would make the update for us, we will update this repository.

Regards
